//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_FLUJOCAJAEntities : DbContext
    {
        public DB_FLUJOCAJAEntities()
            : base("name=DB_FLUJOCAJAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_BANCOS> TB_BANCOS { get; set; }
        public virtual DbSet<TB_CATEGORIAS> TB_CATEGORIAS { get; set; }
        public virtual DbSet<TB_CUENTAS_BANCARIAS> TB_CUENTAS_BANCARIAS { get; set; }
        public virtual DbSet<TB_HISTORIAL_ACCIONES> TB_HISTORIAL_ACCIONES { get; set; }
        public virtual DbSet<TB_OPERACIONES> TB_OPERACIONES { get; set; }
        public virtual DbSet<TB_PERMISOS> TB_PERMISOS { get; set; }
        public virtual DbSet<TB_ROLES> TB_ROLES { get; set; }
        public virtual DbSet<TB_TIPOS_CUENTAS> TB_TIPOS_CUENTAS { get; set; }
        public virtual DbSet<TB_TIPOS_FLUJOS> TB_TIPOS_FLUJOS { get; set; }
        public virtual DbSet<TB_USUARIO> TB_USUARIO { get; set; }
    }
}
