//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_FLUJOCAJAEntities : DbContext
    {
        public DB_FLUJOCAJAEntities()
            : base("name=DB_FLUJOCAJAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_BANCOS> TB_BANCOS { get; set; }
        public virtual DbSet<TB_CATEGORIAS> TB_CATEGORIAS { get; set; }
        public virtual DbSet<TB_CUENTAS_BANCARIAS> TB_CUENTAS_BANCARIAS { get; set; }
        public virtual DbSet<TB_HISTORIAL_ACCIONES> TB_HISTORIAL_ACCIONES { get; set; }
        public virtual DbSet<TB_OPERACIONES> TB_OPERACIONES { get; set; }
        public virtual DbSet<TB_PERMISOS> TB_PERMISOS { get; set; }
        public virtual DbSet<TB_ROLES> TB_ROLES { get; set; }
        public virtual DbSet<TB_TIPOS_CUENTAS> TB_TIPOS_CUENTAS { get; set; }
        public virtual DbSet<TB_TIPOS_FLUJOS> TB_TIPOS_FLUJOS { get; set; }
        public virtual DbSet<TB_USUARIO> TB_USUARIO { get; set; }
    
        public virtual int SP_TB_CUENTAS_BANCARIAS_INSERT(Nullable<decimal> id_tipo_cuenta, Nullable<decimal> id_banco, Nullable<double> saldo)
        {
            var id_tipo_cuentaParameter = id_tipo_cuenta.HasValue ?
                new ObjectParameter("id_tipo_cuenta", id_tipo_cuenta) :
                new ObjectParameter("id_tipo_cuenta", typeof(decimal));
    
            var id_bancoParameter = id_banco.HasValue ?
                new ObjectParameter("id_banco", id_banco) :
                new ObjectParameter("id_banco", typeof(decimal));
    
            var saldoParameter = saldo.HasValue ?
                new ObjectParameter("saldo", saldo) :
                new ObjectParameter("saldo", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_CUENTAS_BANCARIAS_INSERT", id_tipo_cuentaParameter, id_bancoParameter, saldoParameter);
        }
    
        public virtual int SP_TB_CUENTAS_BANCARIAS_UPDATE(Nullable<decimal> id_cuenta_bancaria, string numero_cuenta, Nullable<decimal> id_tipo_cuenta, Nullable<decimal> id_banco, Nullable<double> saldo)
        {
            var id_cuenta_bancariaParameter = id_cuenta_bancaria.HasValue ?
                new ObjectParameter("id_cuenta_bancaria", id_cuenta_bancaria) :
                new ObjectParameter("id_cuenta_bancaria", typeof(decimal));
    
            var numero_cuentaParameter = numero_cuenta != null ?
                new ObjectParameter("numero_cuenta", numero_cuenta) :
                new ObjectParameter("numero_cuenta", typeof(string));
    
            var id_tipo_cuentaParameter = id_tipo_cuenta.HasValue ?
                new ObjectParameter("id_tipo_cuenta", id_tipo_cuenta) :
                new ObjectParameter("id_tipo_cuenta", typeof(decimal));
    
            var id_bancoParameter = id_banco.HasValue ?
                new ObjectParameter("id_banco", id_banco) :
                new ObjectParameter("id_banco", typeof(decimal));
    
            var saldoParameter = saldo.HasValue ?
                new ObjectParameter("saldo", saldo) :
                new ObjectParameter("saldo", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_CUENTAS_BANCARIAS_UPDATE", id_cuenta_bancariaParameter, numero_cuentaParameter, id_tipo_cuentaParameter, id_bancoParameter, saldoParameter);
        }
    }
}
