//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CUENTAS_BANCARIAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CUENTAS_BANCARIAS()
        {
            this.TB_OPERACIONES = new HashSet<TB_OPERACIONES>();
        }
    
        public decimal ID_TIPO_CUENTA { get; set; }
        public decimal ID_BANCO { get; set; }
        public decimal ID_CUENTA_BANCARIA { get; set; }
        public Nullable<double> SALDO { get; set; }
        public Nullable<int> USUARIO_INSERT { get; set; }
        public Nullable<System.DateTime> FECHA_INSERT { get; set; }
    
        public virtual TB_BANCOS TB_BANCOS { get; set; }
        public virtual TB_TIPOS_CUENTAS TB_TIPOS_CUENTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_OPERACIONES> TB_OPERACIONES { get; set; }
    }
}
