//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CATEGORIAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CATEGORIAS()
        {
            this.TB_OPERACIONES = new HashSet<TB_OPERACIONES>();
        }
    
        public decimal ID_CATEGORIA { get; set; }
        public Nullable<decimal> ID_TIPO_FLUJO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> USUARIO_INSERT { get; set; }
        public Nullable<System.DateTime> FECHA_INSERT { get; set; }
    
        public virtual TB_TIPOS_FLUJOS TB_TIPOS_FLUJOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_OPERACIONES> TB_OPERACIONES { get; set; }
    }
}
