//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_OPERACIONES
    {
        public decimal ID_TIPO_CUENTA { get; set; }
        public decimal ID_BANCO { get; set; }
        public decimal ID_CUENTA_BANCARIA { get; set; }
        public decimal ID_OPERACION { get; set; }
        public Nullable<decimal> ID_CATEGORIA { get; set; }
        public Nullable<double> MONTO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> USUARIO_INSERT { get; set; }
        public Nullable<System.DateTime> FECHA_INSERT { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<bool> APROBADO { get; set; }
    
        public virtual TB_CATEGORIAS TB_CATEGORIAS { get; set; }
        public virtual TB_CUENTAS_BANCARIAS TB_CUENTAS_BANCARIAS { get; set; }
    }
}
